export interface Player {
  BirthCity?: string;
  BirthCountry?: string;
  BirthDate?: string;
  CommonName?: string;
  DraftKingsPosition?: string;
  FirstName?: string;
  Foot?: string;
  Gender?: string;
  Height?: number;
  InjuryBodyPart?: string;
  InjuryNotes?: string;
  InjuryStartDate?: string | null;
  InjuryStatus?: string;
  Jersey?: number;
  LastName?: string;
  Nationality?: string;
  PhotoUrl?: string;
  PlayerId?: number;
  Position?: string;
  PositionCategory?: string;
  RotoWirePlayerID?: number;
  ShortName?: string;
  Updated?: string;
  UsaTodayHeadshotNoBackgroundUpdated?: string | null;
  UsaTodayHeadshotNoBackgroundUrl?: string | null;
  UsaTodayHeadshotUpdated?: string | null;
  UsaTodayHeadshotUrl?: string | null;
  UsaTodayPlayerID?: number;
  Weight?: number;
}

export type Club = {
  Active?: boolean;
  Address?: string;
  AreaId?: number;
  AreaName?: string;
  City?: string;
  ClubColor1?: string;
  ClubColor2?: string;
  ClubColor3?: string;
  Email?: string;
  Fax?: string;
  Founded?: number;
  FullName?: string;
  Gender?: string;
  GlobalTeamId?: number;
  Key?: string;
  Name?: string;
  Nickname1?: string;
  Nickname2?: string;
  Nickname3?: string;
  Phone?: string;
  TeamId?: number;
  Type?: string;
  VenueId?: number;
  VenueName?: string;
  Website?: string;
  WikipediaLogoUrl?: string;
  WikipediaWordMarkUrl?: string;
  Zip?: string;
};
